---
title: "Rodada 2 - LabEst"
output: html_document
header-includes:
   - \usepackage{longtable}
   - \usepackage{graphicx}
---

```{r setup, include=FALSE, echo = TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(skimr)
library(DT)
library(gt)
library(gtsummary)
library(kableExtra)
library(reshape2)
```


# Importação e preparação dos dados

```{r}
data <- readxl::read_xls("data/BAYLEY TRIAGEM AUDITIVA ANÁLISE ESTATÍSTICA 16052025.xls") %>% 
  janitor::clean_names()

derivadas_classificacao <- c(
  "pontosabep36", "somaludicas36",
  "cogbal36", "cogcomp36", "lrbal36", "lebal36",
  "lingcomp36", "mfbal36", "mgbal36", "motorcomp36")

data <- data %>% 
  dplyr::select(-any_of(derivadas_classificacao)) %>%
  dplyr::mutate(across(everything(), ~ifelse(. == 'Missing', NA, .)))
```

# Dicionário das variáveis

```{r}
dict <- tribble(
  ~Variavel, ~Explicacao, ~Categorias,
  "idademaecat", "Idade da mãe (Adulta: 1, Adolescente: 0)", "1: adulta, 0: adolescente",
  "pesocat", "Peso ao nascimento (> ou igual 2500g: 1; <2500g: 0)", "1: >=2500g, 0: <2500g",
  "igcat", "Idade gestacional ao nascimento (> ou igual 37s: 1; <37s: 0)", "1: >=37s, 0: <37s",
  "partocat", "Via de parto (vaginal/fórceps: 1, cesariana: 0)", "1: vaginal/fórceps, 0: cesariana",
  "lme6", "Aleitamento materno exclusivo aos 6 meses", "1: sim, 0: não",
  "corcat24", "Etnia (branco: 1, não branco: 0)", "1: branco, 0: não branco",
  "estadocivilmae24", "Estado civil mãe (casada/união estável: 1, solteira/divorciada: 0)", "1: casada/união, 0: solteira/div.",
  "escolamaecat36", "Escolaridade mãe (2: superior/pos, 1: médio, 3: fundamental)", "2: superior/pós, 1: médio, 3: fundamental",
  "abepcat36", "Classe social (A, B, C, DE)", "A, B, C, DE",
  "tanu", "Triagem Auditiva Neonatal Universal", "Sim/Não",
  "resultadotanu", "Resultado TANU", "Sim/Não",
  "resultqtai36", "Resultado QTAI", "Positiva/Negativa",
  "creche36", "Frequenta creche?", "Sim/Não",
  "ludicascat36", "Atividades lúdicas (adequada: 4+, inadequada: 1-3)", "adequada/inadequada",
  "tempotelacat36", "Tempo tela <1h/dia (1: usa 1h+, 0: menos de 1h)", "1: >=1h, 0: <1h",
  "horacertacat36", "Horário fixo para telas (1: sim, 0: não)", "1: sim, 0: não",
  "telacasa36", "Como usa telas em casa", "Adultos/Outra criança/Sozinho",
  "telalimitetempocat36", "Limite de tempo pelos cuidadores", "1: sim, 0: não",
  "telainteraçãocat36", "Interagem na tela?", "1: sim, 0: não",
  "telalimiteconteudocat36", "Limitam o conteúdo?", "1: sim, 0: não",
  "pedsqlfisico36", "Escala PEDSQL Físico (contínua)", "0-100",
  "pedsqlpsico36", "Escala PEDSQL Psicológico (contínua)", "0-100",
  "pedsqlglobal36", "Escala PEDSQL Global (contínua)", "0-100",
  "genero", "Gênero da criança", "Feminino/Masculino",
  "classcogbal36", "Desenvolvimento Cognitivo", "1: normal, 0: atraso",
  "classcogcomp36", "Desenvolvimento Cognitivo Composto", "1: normal, 0: atraso",
  "claslrbal36", "Domínio Linguagem Receptiva", "1: normal, 0: atraso",
  "classlebal36", "Domínio Linguagem Expressiva", "1: normal, 0: atraso",
  "classlingcomp36", "Domínio Linguagem Composto", "1: normal, 0: atraso",
  "classmfbal36", "Domínio Motricidade Fina", "1: normal, 0: atraso",
  "classmgbal36", "Domínio Motricidade Grossa", "1: normal, 0: atraso",
  "classmotorcomp36", "Domínio Motricidade Composta", "1: normal, 0: atraso"
)
knitr::kable(dict, caption = "Dicionário resumido das variáveis") %>% kableExtra::kable_styling()
```

# Análise Univariada

## Variaveis Categóricas

```{r}
vars_categoricas <- c(
  "idademaecat", "pesocat", "igcat", "partocat", "lme6", "corcat24", "estadocivilmae24",
  "escolamaecat36", "abepcat36", "tanu", "resultadotanu", "resultqtai36", "creche36",
  "ludicascat36", "tempotelacat36", "horacertacat36", "telacasa36", "telalimitetempocat36",
  "telainteracaocat36", "telalimiteconteudocat36", "genero", 
  "classcogbal36", "classcogcomp36", "claslrbal36", "classlebal36", "classlingcomp36",
  "classmfbal36", "classmgbal36", "classmotorcomp36"
)
categoricas <- data %>% dplyr::select(all_of(vars_categoricas))

for(n in vars_categoricas) {
  cat("###", n, "\n")
  print(knitr::kable(table(data[[n]], useNA = "ifany"),
                     caption = paste("Tabela de Frequência para", n)))
  cat("\n\n")
}
```

## Variaveis Numéricas

```{r}
vars_numericas <- c("pedsqlfisico36", "pedsqlpsico36", "pedsqlglobal36")
numericas <- data %>% dplyr::select(all_of(vars_numericas))
summary(numericas) %>%
  knitr::kable(caption = "Sumário estatístico das variáveis numéricas/resposta") %>%
  kableExtra::kable_styling()
```

# Variáveis resposta

```{r}
# respostas = numericas
vars_resposta <- c("pedsqlfisico36", "pedsqlglobal36", "pedsqlpsico36")

data_long <- data %>%
  dplyr::select(all_of(vars_resposta)) %>%
  tidyr::pivot_longer(cols = everything(), names_to = "Escala", values_to = "Score")

ggplot(data_long, aes(x = Score, fill = Escala)) +
  geom_histogram(bins = 20, alpha = 0.6) +
  facet_wrap(~Escala, scales = "free") +
  theme_minimal() +
  labs(title = "Distribuição das Escalas PEDSQL", x = "Score", y = "Frequência") +
  theme(legend.position = "none")
```

```{r}
ggplot(data_long, aes(x = Escala, y = Score, fill = Escala)) +
  geom_boxplot(alpha = 0.7) +
  theme_minimal() +
  labs(title = "Boxplot das Escalas PEDSQL", x = "Escala", y = "Score") +
  theme(legend.position = "none")
```

# Associação das variáveis resposta (pedsqlglobal36)

## Por gênero

```{r}
# Removi a tabela pois achei confusa a interpretacao da mediana/quantis
# data %>%
#   select(genero, all_of(vars_resposta)) %>%
#   tbl_summary(by = genero, missing = "no") %>%
#   add_overall() %>%
#   bold_labels()
```

```{r}
ggplot(data, aes(x = genero, y = pedsqlglobal36, fill = genero)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "PEDSQL Global por Gênero", x = "Gênero", y = "PEDSQL Global", fill = "Gênero")
```

## Por Faixa Etária Materna

```{r}
idademaecat_label <- c("1" = "Adulta", "0" = "Adolescente")

data %>%
  dplyr::mutate(idademaecat_lab = recode(as.character(idademaecat), !!!idademaecat_label)) %>%
  ggplot(aes(x = idademaecat_lab, y = pedsqlglobal36, fill = idademaecat_lab)) +
  geom_boxplot() +
  theme_minimal() +
  labs(
    title = "PEDSQL Global por Faixa Etária Materna",
    x = "Faixa Etária Materna",
    y = "PEDSQL Global",
    fill = "Faixa Etária Materna"
  ) +
  theme(legend.position = "bottom")
```

## Por Idade Gestacional

```{r}
igcat_labels <- c("0" = "< 37 semanas", "1" = ">= 37 semanas")

data %>%
  mutate(igcat_lab = recode(as.character(igcat), !!!igcat_labels)) %>%
  ggplot(aes(x = igcat_lab, y = pedsqlglobal36, fill = igcat_lab)) +
  geom_boxplot() +
  theme_minimal() +
  labs(
    title = "PEDSQL Global por Idade Gestacional",
    x = "Idade Gestacional",
    y = "PEDSQL Global",
    fill = "Idade Gestacional"
  ) +
  theme(legend.position = "bottom")
```

## Por Tipo de Parto

```{r}
partocat_labels <- c("0" = "Cesárea", "1" = "Vaginal/Forcéps")

data %>%
  mutate(partocat_lab = recode(as.character(partocat), !!!partocat_labels)) %>%
  ggplot(aes(x = partocat_lab, y = pedsqlglobal36, fill = partocat_lab)) +
  geom_boxplot() +
  theme_minimal() +
  labs(
    title = "PEDSQL Global por Tipo de Parto",
    x = "Tipo de Parto",
    y = "PEDSQL Global",
    fill = "Tipo de Parto"
  ) +
  theme(legend.position = "bottom")
```

# Correlação entre as escalas PEDSQL

```{r}
label_resposta <- c(
  "pedsqlfisico36" = "Escore Físico",
  "pedsqlpsico36" = "Escore Psicossocial",
  "pedsqlglobal36" = "Escore Global")

cor_mat <- data %>% dplyr::select(all_of(vars_resposta)) %>%
  cor(use = "pairwise.complete.obs")
cor_long <- melt(cor_mat)
colnames(cor_long) <- c("Var1", "Var2", "Correlacao")

cor_long$Var1 <- label_resposta[as.character(cor_long$Var1)]
cor_long$Var2 <- label_resposta[as.character(cor_long$Var2)]

ggplot(cor_long, aes(x = Var1, y = Var2, fill = Correlacao)) +
  geom_tile(color = "white") +
  geom_text(aes(label = sprintf("%.2f", Correlacao)), size = 5, color = "black") +
  scale_fill_gradient2(low = "red", high = "blue", mid = "white", midpoint = 0,
                       limits = c(-1,1), name = "Correlação") +
  theme_minimal(base_size = 14) +
  labs(title = "Matriz de Correlação entre as Escalas PEDSQL", x = "", y = "")
```

